---
- hosts: webserver
  become: yes
  tasks: 
  - name: copy artifacts from nexus to tomcat
    get_url: 
      url: http://13.231.2.234:8081/nexus/service/local/repositories/jaga/content/KODDAS/hello-world-war/51/hello-world-war-51.war
      dest: /usr/share/tomcat/webapps
      url_username: jaga
      url_password: jaga
     
  - name: restart tomcat
    service: 
      name: tomcat
      state: restarted
